M48
; DRILL file {KiCad 6.0.9-8da3e8f707~117~ubuntu20.04.1} date Tue 07 Mar 2023 09:14:25 AM EST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-03-07T09:14:25-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.9-8da3e8f707~117~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1181
%
G90
G05
T1
X5.452Y-3.4508
X6.1831Y-2.9291
X6.312Y-5.4764
T0
M30
